services:
  auth-postgres:
    image: postgres:14
    container_name: auth-postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - './docker/initdb:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432'

volumes:
  auth_db_data:
    name: auth_db_data
