services:
  postgres:
    image: postgres:14
    container_name: auth-postgres
    restart: always
    env_file:
      - ./.env # define POSTGRES_USER, POSTGRES_PASSWORD, etc.
    volumes:
      - db-data:/var/lib/postgresql/data
      - './docker/initdb:/docker-entrypoint-initdb.d' # tu init scripts
    ports:
      - '5432:5432'

volumes:
  db-data:
    name: postgres_data
